server:
  port: 8080
  servlet:
    context-path: /traffic-config

# WebSocket配置
websocket:
  traffic:
    endpoint: /ws/traffic
    allowed-origins: "*"  # 生产环境应配置具体域名
    max-session-idle-timeout: 30000
    max-text-message-buffer-size: 8192
    max-binary-message-buffer-size: 8192

spring:
  application:
    name: traffic-config-system
  profiles:
    active: default # 不包含statemachine-v2，所以statemachinev2不会启动

# 配置文件路径
traffic:
  config:
    file:
      path: classpath:config.xml

logging:
  level:
    com.traffic: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"